wallpaper {
  monitor = eDP-1
    path = ~/Downloads/somewhere-in-time-cover-art.jpg
    fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
    path = ~/Downloads/stranger_in_a_stranger_land.jpeg
    fit_mode = cover
}
